### ISSUE TITLE
the code does not work :(

### ISSUE THREAD

**Issue by YorksonChang** [corwinliu9669/embarrassingly-simple-baseline#1]
Hey, have you finished the code? It seems like not completed.

**Comment by corwinliu9669** [comment]
sorry, i have not upload the complete code.

**Comment by corwinliu9669** [comment]
I will finish it this week. By the way, can you show me your concrete problem.

**Comment by YorksonChang** [comment]
for example,

**Comment by corwinliu9669** [comment]
It's my fault. I forgot to upload utils.py. Because code of this work is mixed with other work's code.
 And you are right, firstly run pretrain_model.py and then test_pretrain_model.py.
