### ISSUE TITLE
Where can I obtain the pickle files?

### ISSUE THREAD

**Issue by er537** [corwinliu9669/embarrassingly-simple-baseline#2]
Could you point me in the direction of where I can obtain the miniImageNet pickle files from, or how you generated them? Thank you.

**Comment by DessiLBI2020** [comment]
Please refer to https://github.com/gidariss/FewShotWithoutForgetting.

**Comment by corwinliu9669** [comment]
Please refer to https://github.com/gidariss/FewShotWithoutForgetting.
